name: Build and Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download core JAR
        run: bash scripts/download-core.sh

      - name: Install core JAR to local repository
        run: mvn install:install-file -Dfile=libs/core-0.3.6.jar -DgroupId=com.looksee -DartifactId=core -Dversion=0.3.6 -Dpackaging=jar
      
      - name: Test with Maven
        run: mvn test

  bump-version:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Determine and bump version with Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Extract new version from pom.xml
        id: get_version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"
          
  docker-release:
    needs: bump-version
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.bump-version.outputs.VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Docker image
        run: |
          docker build -t deepthought42/audit-update-service:${{ env.VERSION }} .
          docker tag deepthought42/audit-update-service:${{ env.VERSION }} deepthought42/audit-update-service:latest

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push deepthought42/audit-update-service:${{ env.VERSION }}
          docker push deepthought42/audit-update-service:latest
      
  github-release:
    needs: bump-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      VERSION: ${{ needs.bump-version.outputs.VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make download script executable
        run: chmod +x scripts/download-core.sh

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Download core JAR
        run: bash scripts/download-core.sh

      - name: Install core JAR to local repository
        run: mvn install:install-file -Dfile=libs/core-0.3.6.jar -DgroupId=com.looksee -DartifactId=core -Dversion=0.3.6 -Dpackaging=jar
      
      - name: Maven install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.actor }}
        run: mvn install -DskipTests

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body_path: CHANGELOG.md
          files: audit-update-service-${{ env.VERSION }}.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
